/**
 * @dev This script is designed to test the solidity smart contract - SupplyChain.sol -- and the various functions within
 */

// Import The SC Artifact
var SupplyChain = artifacts.require('SupplyChain');

// Variable for Product States
const State = {
   Harvested: 0,
   Processed: 1,
   Packed: 2,
   ForSale: 3,
   Sold: 4,
   Shipped: 5,
   Received: 6,
   Purchased: 7,
};

contract('SupplyChain', function (accounts) {
   // Declare few constants and assign a few sample accounts generated by ganache-cli
   let sku = 1;
   let upc = 1;
   const ownerID = accounts[0];
   const originFarmerID = accounts[1];
   const originFarmName = 'Abdelhakim Mhioul';
   const originFarmInformation = 'Yarray Valley';
   const originFarmLatitude = '-38.239770';
   const originFarmLongitude = '144.341490';
   let productID = sku + upc;
   const productNotes = 'Best Product';
   const productPrice = web3.utils.toWei('1', 'ether');
   const distributorID = accounts[2];
   const retailerID = accounts[3];
   const consumerID = accounts[4];

   console.log('ganache-cli accounts used here...');
   console.log('Contract Owner: accounts[0] ', accounts[0]);
   console.log('Farmer: accounts[1] ', accounts[1]);
   console.log('Distributor: accounts[2] ', accounts[2]);
   console.log('Retailer: accounts[3] ', accounts[3]);
   console.log('Consumer: accounts[4] ', accounts[4]);

   // 1st Test : For
})