import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Supply Chain Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-blue-600 text-white">Hello There</div>
    </div>
  )
}
