import Head from 'next/head';

// Smart Contracts' ABIs
import SupplyChainContract from '../build/contracts/SupplyChain.json';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Supply Chain Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="m-6 flex flex-col items-center justify-center space-y-4">
        <h1 className="text-5xl font-bold">Fair Trade Coffee</h1>
        <p className="text-xl">
          Prove the authenticity of coffee using the Ethereum blockchain.
        </p>
      </header>
    </div>
  )
}
